### ISSUE TITLE
hopefully you do know such a code in PYTHON?

### ISSUE THREAD

**Issue by Sandy4321** [kliegr/QCBA#1]
Thank you very much for your code
https://cran.r-project.org/web/packages/qCBA/qCBA.pdf
and paper
https://arxiv.org/pdf/1711.10166.pdf
Quantitative CBA: Small and Comprehensible Association Rule Classification Models

Only , hopefully you do know such a code in PYTHON?

**Comment by kliegr** [comment]
Yes, a python implementation is available in the pyARC package (the github version).
https://github.com/jirifilip/pyARC
If you need a an example notebook showing how it can be used, let me know.

**Comment by Sandy4321** [comment]
Great thanks a lot 
It is exactly what I need to learn CBA
And
If you need a an example notebook showing how it can be used, let me know.
Sure this defenetly helps
Also any material

**Comment by Sandy4321** [comment]
Any simple explanation material like students lecture or tutorial  is very welcome

**Comment by kliegr** [comment]
Sorry for taking a bit longer. QCBA is explained in the arxiv paper: https://arxiv.org/abs/1711.10166
A notebook demonstrating how the python implementation can be used is here:
https://github.com/jirifilip/pyARC/blob/master/notebooks/extensions/QCBA_demonstration.ipynb
You can reach out to the pyARC maintainer for any questions.

**Comment by Sandy4321** [comment]
by the way seems to be in 
i https://github.com/jirifilip/pyARC
more  algorithms are used

for example  M1Algorithm, M2Algorithm
pred = m1clf.predict_all(txns_test)

predM2 = m2clf.predict_all(txns_test)
from
https://github.com/jirifilip/pyARC/blob/master/notebooks/extensions/benchmarks/qcba_accuracy_benchmark.ipynb



or not, it is the same as in 
Liu, B. Hsu, W. and Ma, Y (1998). Integrating Classification and Association Rule Mining. Proceedings KDD-98, New York, 27-31 August. AAAI. pp 80-86.

KLIEGR, Tomas. Quantitative CBA: Small and Comprehensible Association Rule Classification Models. arXiv preprint arXiv:1711.10166, 2017
?
